### PR TITLE
NXDRIVE-961: Add auto-update process check script

### PR DESCRIPTION
**Pull request by BoboTiG**

### CODE REVIEW

**Comment by ataillefer** [comment]
Nice! How do you actually check that the emulated old version updates to the newer version?

**Comment by BoboTiG** [comment]
When Drive is launched, you can see traces and it will restart using the new version. Or not, depending an eventual regression. All simply :)

**Comment by BoboTiG** [comment]
I think we can automate the thing and check `ndrive --version`. We will need a way to quit Drive after the update check is done. But for now, it works fine.

**Comment by ataillefer** [comment]
:+1:

**Pull request merged**
