### PR TITLE
NXDRIVE-990: Other docs folder is deleted after disconnect and reconn…

### PR DESCRIPTION
**Pull request by Bindupriya**
…ect with same user in Desktop sync

### CODE REVIEW

**Comment by BoboTiG** [comment]
Hello Bindu,

Thanks for the patch.

Did you check that the issue reported in NXDRIVE-904 is still fixed with those changes?

**Comment by Bindupriya** [comment]
Hello @BoboTiG,

I have added the one more condition check
Please check the link with the highlighted line number #509
https://github.com/nuxeo/nuxeo-drive/pull/299/files#diff-3ac0d3ca326afdda837555bfc7266b34R509

**Comment by BoboTiG** [comment]
OK, I format your patch and merge. Thanks :)

**Comment by Bindupriya** [comment]
Thank you

**Comment by BoboTiG** [comment]
Closing this PR for #300 (updated changes and version).

**Pull request closed without merging**
