### PR TITLE
NXDRIVE-728: Add support for proxy PAC url

### PR DESCRIPTION
**Pull request by rajadg**

### CODE REVIEW

**Comment by BryanSchacht** [comment]
I think Sharp already signed the CLA for Drive some time ago.

Bryan

Sent from BlueMail<http://www.bluemail.me/r?b=8872>
On Feb 22, 2017, at 1:57 AM, CLAassistant <notifications@github.com<mailto:notifications@github.com>> wrote:

[CLA assistant check]<https://cla-assistant.io/nuxeo/nuxeo-drive?pullRequest=139>
Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement<https://cla-assistant.io/nuxeo/nuxeo-drive?pullRequest=139> before we can accept your contribution.

**Comment by loopingz** [comment]
The CLA signature is an automated bot, so even if Sharp has signed it, it will require every contributor to do so too. It is part of a newly process put in place by Nuxeo. Even myself had to sign the CLA to please this bot.

Regards

**Comment by BryanSchacht** [comment]
The new overlord's.. 😀

Bryan

Sent from BlueMail<http://www.bluemail.me/r?b=8872>
On Feb 22, 2017, at 12:18 PM, Remi Cattiau <notifications@github.com<mailto:notifications@github.com>> wrote:

The CLA signature is an automated bot, so even if Sharp has signed it, it will require every contributor to do so too. It is part of a newly process put in place by Nuxeo. Even myself had to sign the CLA to please this bot.

Regards

**Comment by rajadg** [comment]
I read the CLA, then signed into github to accept the CLA. After this the pull request #139 page reloaded and still the status is 'CLA not signed yet'. I attempted again, but now I see only the CLA terms. There is no sign in option to sign the CLA. What should I do?

**Comment by rajadg** [comment]
Till now I have signed CLA more than 5 times. But after signing the CLA, the github redirects to this PR page and then it shows CLA not signed. Am I missing something?

**Comment by jcarsique** [comment]
Hi,

About the CLA, we moved from a per-repository to a per-organization hook; as a consequence, the CLA has been required twice on some pull requests. Apologizes.

This must be fixed now. The above CLA status seems fine.

Best regards

**Comment by BoboTiG** [comment]
:+1:

**Comment by ataillefer** [comment]
:+1:

**Pull request merged**
