### PR TITLE
Added Basque (eu) localization.

### PR DESCRIPTION
**Pull request by aritu**
Please add Basque localization. We could not localize Nuxeo Drive from Crowdin because our language is not available in the project, so we open this pull request. It would be easier for us to be able to update the localization from Crowdin though.
Thanks,

### CODE REVIEW

**Comment by manonlumeau** [comment]
Hi, 

As requested, I activated the Basque as a target language on Crowdin side. You should be able to contribute directly by following [this link](https://crwd.in/nuxeo-drive). 
 
Don't hesitate to let me know if you face any issue. 

Regards, 
Manon

**Comment by BoboTiG** [comment]
Thanks for your contrinution @aritu :)

Manon enabled the Crowdin language. Then you just need to do the work on Crowdin.
There is an automated job that will create a PR with all language changes every day, so you do not need to do more actions on GitHub, everything will be handled for you ;)

**Comment by aritu** [comment]
Ok! Thank you both very much!

**Comment by BoboTiG** [comment]
@aritu, Basque will available to the alpha version of tomorrow. There are only approved sentences (25% for now). When more sentences will be approved later, changes will be available in the alpha of the next day, automatically managed.

**Comment by aritu** [comment]
Ok, thank you @BoboTiG!
I will continue reviewing the localization to have Nuxeo Drive fully in Basque.

**Pull request closed without merging**
